#define DLLExport __declspec(dllexport)



DLLExport void KeyboardPress(int keycode);
DLLExport void KeyboardRelease(int keycode);
DLLExport void MousePress(int keycode);
DLLExport void MouseRelease(int keycode);
DLLExport void MouseMoveTo(long x, long y);
DLLExport void MouseMoveBy(long x, long y);
DLLExport void MouseScroll(int amount, bool asClicks);

enum key {
	TAB = '\t', // int value of 9
	SPACE = ' ',
	QUOTATION = '\'',
	COMMA = ',',
	DASH = '-',
	DOT = '.',
	FORWARD_SLASH = '/',
	ROW_0 = '0',
	ROW_1 = '1',
	ROW_2 = '2',
	ROW_3 = '3',
	ROW_4 = '4',
	ROW_5 = '5',
	ROW_6 = '6',
	ROW_7 = '7',
	ROW_8 = '8',
	ROW_9 = '9',
	SEMICOLON = ';',
	EQUAL = '=',
	A = 'A',
	B = 'B',
	C = 'C',
	D = 'D',
	E = 'E',
	F = 'F',
	G = 'G',
	H = 'H',
	I = 'I',
	J = 'J',
	K = 'K',
	L = 'L',
	M = 'M',
	N = 'N',
	O = 'O',
	P = 'P',
	Q = 'Q',
	R = 'R',
	S = 'S',
	T = 'T',
	U = 'U',
	V = 'V',
	W = 'W',
	X = 'X',
	Y = 'Y',
	Z = 'Z',
	OPEN_BRACKET = '[',
	BACK_SLASH = '\\',
	CLOSE_BRACKET = ']',
	GRAVE = '`',
	ESCAPE,
	F1,
	F2,
	F3,
	F4,
	F5,
	F6,
	F7,
	F8,
	F9,
	F10,
	F11,
	F12,
	BACKSPACE,
	CAPS_LOCK,
	ENTER,
	LEFT_CONTROL,
	LEFT_SYSTEM, //note: no corresponding right key
	LEFT_ALTERNATE,
	LEFT_SHIFT,
	RIGHT_CONTROL,
	RIGHT_ALTERNATE,
	RIGHT_SHIFT,
	INSERT,
	HOME,
	PAGE_UP,
	PAGE_DOWN,
	DEL,
	END,
	LEFT_ARROW,
	UP_ARROW,
	DOWN_ARROW,
	RIGHT_ARROW,
	NUMBER_LOCK,
	PAD_BACKSLASH,
	PAD_STAR,
	PAD_DASH,
	PAD_ADD,
	PAD_ENTER,
	PAD_0,
	PAD_1,
	PAD_2,
	PAD_3,
	PAD_4,
	PAD_5,
	PAD_6,
	PAD_7,
	PAD_8,
	PAD_9,
	PAD_PERIOD, // int value of 146
};